import { CATEGORIES } from "@/lib/constants";
import type { Store } from "@/lib/schema";

/* First-run copy only. After data/store.json exists, updating this file
   does not replace admin edits. Change the live tracker on the Admin page.
*/
const clear = { riskFlag: false, riskNote: "", verified: false, network: "" } as const;

export const SEED = {
  meta: {
    updated: "2026-09-25",
    chain: "gnoland-1",
    rpc: "https://rpc.gno.land:443",
    mainnet: "2026-09-12",
    revision: 6,
  },
  categories: [...CATEGORIES],
  copy: {
    title: "Gnoland Ecosystem Tracker",
    eyebrow: "Gno.land mainnet · gnoland-1 · live 12 Sep 2026",
    subtitle:
      "Projects building on Gno.land, grouped by category.",
    legend: "Grouped by category. A project in more than one category appears in each row.",
    footerNote: "Not investment advice · DYOR",
    updateHint: "Sign in as admin to add or edit projects.",
    searchPlaceholder: "Search projects, teams, realms, X...",
    empty: "No projects match this filter.",
  },
  sources: [
    { label: "gno.land", href: "https://gno.land/" },
    { label: "Ecosystem", href: "https://gno.land/ecosystem" },
    { label: "awesome-gno", href: "https://github.com/gnoverse/awesome-gno" },
    { label: "New Tendermint", href: "https://newtendermint.org/" },
    { label: "Docs", href: "https://docs.gno.land/" },
    { label: "X", href: "https://x.com/_gnoland" },
  ],
  projects: [
    {
      id: "gnoweb",
      name: "Gnoweb",
      status: "Live",
      categories: ["Infra"],
      score: 95,
      oneLiner: "Official web UI for browsing realms, packages, and on-chain source.",
      team: "Gno.land core",
      website: "https://gno.land",
      github: "https://github.com/gnolang/gno",
      x: "https://x.com/_gnoland",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "/",
      alsoPath: "",
      lastUpdated: "2026-09-12",
      notes: "Mainnet is served at gno.land since 12 Sep 2026. The default door into the chain.",
      logo: "/logos/gnolang.png",
      ...clear,
      network: "mainnet",
    },
    {
      id: "gnoscan",
      name: "Gnoscan",
      status: "Live",
      categories: ["Explorer"],
      score: 93,
      oneLiner: "A block explorer for Gno.land.",
      team: "Onbloc",
      website: "https://gnoscan.io",
      github: "https://github.com/onbloc/gnoscan",
      x: "https://x.com/onblocxyz",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-16",
      notes: "The most-used infrastructure alongside Adena. Supports mainnet and staging.",
      logo: "/logos/gnoscan.svg",
      ...clear,
      network: "mainnet",
    },
    {
      id: "adena",
      name: "Adena",
      status: "Live",
      categories: ["Wallet"],
      score: 92,
      oneLiner: "Flagship non-custodial Web3 wallet for Gno.land.",
      team: "Onbloc",
      website: "https://www.adena.app",
      github: "https://github.com/onbloc/adena-wallet",
      x: "https://x.com/onblocxyz",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-23",
      notes: "Chrome extension. The default wallet in the ecosystem right now.",
      logo: "/logos/adena.svg",
      ...clear,
      network: "mainnet",
    },
    {
      id: "gnoswap",
      name: "GnoSwap",
      status: "Live",
      categories: ["DeFi"],
      score: 90,
      oneLiner: "Concentrated liquidity AMM, audited by OpenZeppelin.",
      team: "GnoSwap Labs / Onbloc",
      website: "https://beta.gnoswap.io",
      github: "https://github.com/gnoswap-labs/gnoswap",
      x: "https://x.com/gnoswaplabs",
      discord: "",
      telegram: "",
      docs: "https://docs.gnoswap.io",
      worksWith: [],
      realm: "gno.land/r/gnoswap",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes:
        "The first high-performance concentrated liquidity AMM on Gno.land. Also listed at gnoswap.io. Announced live on mainnet 16 Sep 2026. Two OpenZeppelin audits. Token $GNS. Docs: https://docs.gnoswap.io",
      logo: "/logos/gnoswap.png",
      ...clear,
      network: "mainnet",
    },
    {
      id: "playground",
      name: "Gno Playground",
      status: "Live",
      categories: ["DevTool"],
      score: 88,
      oneLiner: "Browser-based developer tool to write, test, share, and deploy snippets.",
      team: "Gno.land core",
      website: "https://play.gno.land",
      github: "https://github.com/gnolang/gno",
      x: "https://x.com/_gnoland",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-12",
      notes: "Lowers the barrier for new builders. The main developer onboarding tool after docs.gno.land.",
      logo: "/logos/gnolang.png",
      ...clear,
    },
    {
      id: "gnodev",
      name: "gnodev",
      status: "Live",
      categories: ["DevTool"],
      score: 86,
      oneLiner: "Local dev environment with hot reload for realms and packages.",
      team: "Gno.land core",
      website: "https://docs.gno.land",
      github: "https://github.com/gnolang/gno",
      x: "https://x.com/_gnoland",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-12",
      notes: "Use this to build a real app. This is not the gnoland node binary.",
      logo: "/logos/gnolang.png",
      ...clear,
    },
    {
      id: "gnoverse",
      name: "Gnoverse",
      status: "Live",
      categories: ["Community"],
      score: 84,
      oneLiner: "Community GitHub org for tooling, apps, and awesome-gno.",
      team: "Community",
      website: "https://github.com/gnoverse",
      github: "https://github.com/gnoverse/awesome-gno",
      x: "https://x.com/_gnoland",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-23",
      notes: "Main door for finding new projects. Watch the awesome-gno repo.",
      logo: "/logos/gnoverse.png",
      ...clear,
    },
    {
      id: "boards",
      name: "Boards",
      status: "Live",
      categories: ["Social"],
      score: 82,
      oneLiner: "Fully on-chain forum and knowledge system for community publishing and discussion.",
      team: "Gno.land core",
      website: "https://gno.land/r/gnoland/boards2/v1",
      github: "https://github.com/gnolang/gno",
      x: "https://x.com/_gnoland",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "gno.land/r/gnoland/boards2/v1",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "Showcases transparent, community-run publishing and discussion. The current realm is boards2/v1.",
      logo: "/logos/gnolang.png",
      ...clear,
      network: "mainnet",
    },
    {
      id: "govdao",
      name: "GovDAO",
      status: "Live",
      categories: ["Governance"],
      score: 81,
      oneLiner: "Layered governance that separates decision rights from invested capital.",
      team: "Gno.land core",
      website: "https://gno.land",
      github: "https://github.com/gnolang/gno",
      x: "https://x.com/_gnoland",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-16",
      notes: "Mainnet started with a limited tier-1 set. Further members join by proposal.",
      logo: "/logos/gnolang.png",
      ...clear,
      network: "mainnet",
    },
    {
      id: "gnokey",
      name: "gnokey",
      status: "Live",
      categories: ["Wallet"],
      score: 80,
      oneLiner: "Official CLI for key management and transaction signing.",
      team: "Gno.land core",
      website: "https://docs.gno.land",
      github: "https://github.com/gnolang/gno",
      x: "https://x.com/_gnoland",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-12",
      notes: "Adena covers everyday UX. gnokey covers automation, validators, and scripts.",
      logo: "/logos/gnolang.png",
      ...clear,
    },
    {
      id: "gnolove",
      name: "Gnolove",
      status: "Live",
      categories: ["Community"],
      score: 78,
      oneLiner: "Contribution leaderboard and analytics for Gnoland builders.",
      team: "Community",
      website: "https://gnolove.world",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-17",
      notes:
        "Useful for seeing who is shipping code. The site at gnolove.world currently titles itself Memba, a Gno multisig and DAO tool.",
      logo: "",
      ...clear,
    },
    {
      id: "zenao",
      name: "Zenao",
      status: "Live",
      categories: ["Social"],
      score: 76,
      oneLiner: "Events first, then community and social organization.",
      team: "Community",
      website: "https://zenao.io",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-17",
      notes: "Listed on awesome-gno.",
      logo: "/logos/zenao.png",
      ...clear,
    },
    {
      id: "connect",
      name: "Gno Studio Connect",
      status: "Live",
      categories: ["DevTool"],
      score: 74,
      oneLiner: "Call realm functions from the web and inspect contracts without a CLI.",
      team: "Gno.land",
      website: "https://gno.studio/connect",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-17",
      notes: "Some older builds only pointed at a retired testnet. Check the network selector before using mainnet.",
      logo: "/logos/connect.png",
      ...clear,
    },
    {
      id: "status",
      name: "Status",
      status: "Live",
      categories: ["Infra"],
      score: 72,
      oneLiner: "Status dashboard for Gno.land services and the network.",
      team: "Gno.land core",
      website: "https://status.gnoteam.com",
      github: "",
      x: "https://x.com/_gnoland",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-16",
      notes: "The mainnet announcement also pointed at status.gno.land. Use this when RPC, gnoweb, or the indexer looks down.",
      logo: "/logos/gnolang.png",
      ...clear,
    },
    {
      id: "faucet",
      name: "Faucet Hub",
      status: "Live",
      categories: ["Infra"],
      score: 70,
      oneLiner: "Shared faucet for Gno.land testnets.",
      team: "Gno.land core",
      website: "https://faucet.gno.land",
      github: "https://github.com/gnolang/faucet-hub",
      x: "https://x.com/_gnoland",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-12",
      notes: "Mainnet has no faucet. Testnets only.",
      logo: "/logos/gnolang.png",
      ...clear,
      network: "testnet",
    },
    {
      id: "akkadia",
      name: "Akkadia",
      status: "Alpha",
      categories: ["Game"],
      score: 68,
      oneLiner: "Fully on-chain Minecraft built on Gno.land for eternal data preservation.",
      team: "Akkadia",
      website: "https://app.alpha.akkadia.land",
      github: "",
      x: "https://x.com/_akkadia",
      discord: "",
      telegram: "",
      docs: "https://docs.akkadia.land",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-17",
      notes: "One of the earlier creative on-chain apps. Docs: https://docs.akkadia.land",
      logo: "/logos/akkadia.jpg",
      ...clear,
    },
    {
      id: "kourt",
      name: "Kourt",
      status: "Live",
      categories: ["Social", "DeFi"],
      score: 67,
      oneLiner: "A court of record for factual claims, where stake decides which claims get answered and the answer and its route stay on chain.",
      team: "Community",
      website: "https://kourt.xyz",
      github: "https://github.com/jaekwon/kourt",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "gno.land/r/g1ecsuj0q572jr0dhu29q9njtnmw03hyu7tyyvv6/kourt",
      alsoPath: "",
      lastUpdated: "2026-09-17",
      notes: "The realm is on mainnet. Re-check the path if the layout changes.",
      logo: "/logos/kourt.svg",
      ...clear,
      network: "mainnet",
    },
    {
      id: "commondao",
      name: "CommonDAO",
      status: "Dev",
      categories: ["Governance"],
      score: 60,
      oneLiner: "General-purpose DAO implementation for spinning up Gno.land DAO systems.",
      team: "Community",
      website: "https://gno.land/p/nt/commondao/v0",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "gno.land/p/nt/commondao/v0",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "Package docs also live at newtendermint.org. Built for spinning up DAO systems, not only a single end-user app.",
      logo: "/logos/commondao.png",
      ...clear,
      network: "mainnet",
    },
    {
      id: "gnochess",
      name: "GnoChess",
      status: "Dev",
      categories: ["Game"],
      score: 58,
      oneLiner: "Chess server written in Gno, with a frontend, faucet, and tutorial.",
      team: "Gnoverse",
      website: "",
      github: "https://github.com/gnoverse/gnochess",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-17",
      notes: "An education project and a composability demo.",
      logo: "",
      ...clear,
    },
    {
      id: "gnonative",
      name: "Gno Native Kit",
      status: "Dev",
      categories: ["DevTool"],
      score: 57,
      oneLiner: "Framework for taking Gno dApps native, including React Native and Expo.",
      team: "Gno.land",
      website: "https://github.com/gnolang/gnonative",
      github: "https://github.com/gnolang/gnonative",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-17",
      notes: "Mobile infrastructure, not an end-user app yet.",
      logo: "/logos/gnolang.png",
      ...clear,
    },
    {
      id: "openocean",
      name: "OpenOcean",
      status: "Dev",
      categories: ["DeFi", "Marketplace"],
      score: 55,
      oneLiner: "OpenSea-style marketplace written in Gno.",
      team: "Community",
      website: "",
      github: "https://github.com/Molaryy/openocean",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-17",
      notes: "Early NFT marketplace. Frontend and mainnet status still need a fresh check.",
      logo: "",
      ...clear,
    },
    {
      id: "gnomputer",
      name: "Gnomputer",
      status: "Live",
      categories: ["DevTool", "Infra"],
      score: 70,
      oneLiner: "Windowed desktop for the Gno chain, running entirely in the browser.",
      team: "moul",
      website: "https://moul.github.io/gnomputer",
      github: "https://github.com/moul/gnomputer",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "Listed on awesome-gno and gnoverse.",
      logo: "",
      ...clear,
    },
    {
      id: "dsocial",
      name: "dSocial",
      status: "Experimental",
      categories: ["Social"],
      score: 42,
      oneLiner: "Experimental social apps and tools on Gno.",
      team: "Gnoverse",
      website: "",
      github: "https://github.com/gnoverse/dsocial",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-17",
      notes: "Early and experimental.",
      logo: "",
      ...clear,
    },
    {
      id: "memeland",
      name: "meme.land",
      status: "Announced",
      categories: ["Social"],
      score: 35,
      oneLiner: "Photo-sharing app built with Gno plus React/Vue.",
      team: "Gnoverse",
      website: "",
      github: "https://github.com/gnoverse/memeland",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-17",
      notes: "awesome-gno marks the hosted frontend as no longer reaching the chain. Stays in C until it comes back.",
      logo: "",
      ...clear,
    },
    {
      id: "gnobridge",
      name: "GnoBridge",
      status: "Live",
      categories: ["DeFi", "Bridge"],
      score: 76,
      oneLiner: "Bridge between Gno and EVM chains, powered by Union IBC.",
      team: "Onbloc",
      website: "https://bridge.onbloc.xyz/",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "Listed as the bridge between Gno and EVM chains. The site did not respond when checked, so no logo was saved.",
      logo: "",
      ...clear,
    },
    {
      id: "volos",
      name: "Volos",
      status: "Dev",
      categories: ["DeFi"],
      score: 58,
      oneLiner: "The first lending protocol written in Gno, integrated with GnoSwap for price determination.",
      team: "Gnoverse",
      website: "",
      github: "https://github.com/gnoverse/volos",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: ["gnoswap"],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "Source is the gnoverse/volos repository. No separate website is listed.",
      logo: "",
      ...clear,
    },
    {
      id: "gnomi",
      name: "Gnomi",
      status: "Live",
      categories: ["Launchpad"],
      score: 74,
      oneLiner: "Meme launchpad on Gno.land.",
      team: "",
      website: "https://gnomi.fun/",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "Public site is gnomi.fun. The shipped site defaults to Gno mainnet (gnoland-1).",
      logo: "/logos/gnomi.svg",
      ...clear,
      network: "mainnet",
    },
    {
      id: "gnotfun",
      name: "Gnot.fun",
      status: "Live",
      categories: ["Launchpad"],
      score: 64,
      oneLiner: "A launchpad and trading platform for GRC20 tokens.",
      team: "",
      website: "https://www.gnot.fun/",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "The site nav is set to Pearl testnet.",
      logo: "/logos/gnotfun.png",
      ...clear,
      network: "testnet",
    },
    {
      id: "gnomic",
      name: "GNOMIC",
      status: "Live",
      categories: ["Launchpad", "Game", "NFT"],
      score: 63,
      oneLiner: "A token and NFT launchpad.",
      team: "",
      website: "https://gnomic.wtf/",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "The token page says it is live on mainnet. The NFT ring at claim.gnomic.wtf is described as live on testnet.",
      logo: "/logos/gnomic-mark.png",
      ...clear,
      network: "mainnet",
    },
    {
      id: "memba",
      name: "Memba",
      status: "Live",
      categories: ["Governance", "Wallet"],
      score: 73,
      oneLiner: "Gateway to Gno multisig wallets, DAO governance, and token management.",
      team: "",
      website: "https://memba.samourai.app",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "Covers multisig wallets, DAO governance, and token management in one place.",
      logo: "/logos/memba.png",
      ...clear,
    },
    {
      id: "gnobounty",
      name: "Gno Bounty",
      status: "Experimental",
      categories: ["Governance"],
      score: 52,
      oneLiner: "Proof of concept for bounty creation, submission workflows, and DAO-powered review committees.",
      team: "",
      website: "https://gnobounty.vercel.app",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "Described as a proof-of-concept application.",
      logo: "",
      ...clear,
    },
    {
      id: "cyphergnomes",
      name: "Cypher Gnomes",
      status: "Experimental",
      categories: ["Game", "NFT"],
      score: 51,
      oneLiner: "Generates an NFT gnome from a Gno address for minting experiments.",
      team: "",
      website: "https://cyphergnome.netlify.app",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "Generate a gnome from a Gno address and experiment with minting.",
      logo: "/logos/cypher.png",
      ...clear,
    },
    {
      id: "gnomads",
      name: "Gnomads",
      status: "Live",
      categories: ["Game", "NFT"],
      score: 61,
      oneLiner: "A pixel gnome NFT collection on Gno.land.",
      team: "",
      website: "https://gnomads.land",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "The site says mainnet, chain id gnoland-1.",
      logo: "/logos/gnomads.svg",
      ...clear,
      network: "mainnet",
    },
    {
      id: "gnopixels",
      name: "Gno Pixels",
      status: "Live",
      categories: ["Game"],
      score: 65,
      oneLiner: "Collaborative on-chain canvas for Gno.land.",
      team: "",
      website: "https://pixels.gno.observer",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "pixels.gno.observer currently redirects to GnoPulse, so this card keeps the name instead of borrowing that logo.",
      logo: "",
      ...clear,
    },
    {
      id: "gems",
      name: "Gems",
      status: "Live",
      categories: ["Game", "NFT"],
      score: 60,
      oneLiner: "An NFT gem collection where each mint assembles a one-of-a-kind piece on chain.",
      team: "",
      website: "https://gno.tools/gems",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: ["gnotools"],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "Hosted at gno.tools/gems. The mint page says this collection is on the Pearl testnet.",
      logo: "/logos/gems.png",
      ...clear,
      network: "testnet",
    },
    {
      id: "gingegnomie",
      name: "Ginge Gnomie",
      status: "Live",
      categories: ["Game", "NFT"],
      score: 59,
      oneLiner: "An open-mint GRC721 gnome collection on Gno.land.",
      team: "",
      website: "https://gingegnomies.land",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "",
      logo: "",
      ...clear,
    },
    {
      id: "gnonightsky",
      name: "Gno Night Sky",
      status: "Dev",
      categories: ["Social"],
      score: 48,
      oneLiner: "Telescope implementation on Gno.land.",
      team: "Gnoverse",
      website: "",
      github: "https://github.com/gnoverse/gnonightsky",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "Source is the gnoverse/gnonightsky repository.",
      logo: "",
      ...clear,
    },
    {
      id: "historia",
      name: "Historia",
      status: "Live",
      categories: ["Social"],
      score: 62,
      oneLiner: "Immutable registry for stake-based consensus around historical claims.",
      team: "",
      website: "https://historia-gno.vercel.app",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "Designed for stake-based consensus around historical claims.",
      logo: "",
      ...clear,
    },
    {
      id: "gnomcp",
      name: "GnoMCP",
      status: "Live",
      categories: ["DevTool"],
      score: 68,
      oneLiner: "MCP server and agent skill for Gno.land.",
      team: "",
      website: "https://mcp.gno.dev",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "The site says it ships pointed at the public testnet and a local gnodev node.",
      logo: "/logos/gnomcp.svg",
      ...clear,
      network: "testnet",
    },
    {
      id: "gnopls",
      name: "gnopls",
      status: "Dev",
      categories: ["DevTool"],
      score: 56,
      oneLiner: "Language server for Gno, forked from gopls, the official language server of Go.",
      team: "Gnoverse",
      website: "",
      github: "https://github.com/gnoverse/gnopls",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "",
      logo: "",
      ...clear,
    },
    {
      id: "gnox402",
      name: "Gnox402",
      status: "Dev",
      categories: ["DevTool"],
      score: 50,
      oneLiner: "x402 payment protocol for Gno.land.",
      team: "Gnoverse",
      website: "",
      github: "https://github.com/gnoverse/x402",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "",
      logo: "",
      ...clear,
    },
    {
      id: "gnockpit",
      name: "Gnockpit",
      status: "Dev",
      categories: ["Infra", "Validators"],
      score: 49,
      oneLiner: "Real-time Gno.land validator node monitoring web dashboard.",
      team: "Gnoverse",
      website: "",
      github: "https://github.com/gnoverse/gnockpit",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "",
      logo: "",
      ...clear,
    },
    {
      id: "gnoduty",
      name: "Gno Duty",
      status: "Dev",
      categories: ["Infra", "Validators"],
      score: 47,
      oneLiner: "Real-time validator monitoring for Gno.land (TM2) networks.",
      team: "AviaOne",
      website: "",
      github: "https://github.com/AviaOne/GnoDuty",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "",
      logo: "",
      ...clear,
    },
    {
      id: "gnotools",
      name: "Gno.Tools",
      status: "Live",
      categories: ["DevTool", "Infra"],
      score: 71,
      oneLiner: "Read-only tools for Gno.land.",
      team: "",
      website: "https://gno.tools",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "Gems is also hosted under gno.tools/gems.",
      logo: "/logos/gnotools.svg",
      ...clear,
    },
    {
      id: "gnopulse",
      name: "GnoPulse",
      status: "Live",
      categories: ["Explorer"],
      score: 69,
      oneLiner: "The Gno.land blockchain intelligence platform.",
      team: "",
      website: "https://gnopulse.xyz",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "",
      logo: "/logos/gnopulse.png",
      ...clear,
    },
    {
      id: "gnoobserver",
      name: "Gno Observer",
      status: "Live",
      categories: ["Explorer"],
      score: 68,
      oneLiner: "Dashboard for Gno.land’s on-chain activity.",
      team: "",
      website: "https://gno.observer",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: ["gnopulse"],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "gno.observer currently redirects to GnoPulse.",
      logo: "/logos/gnopulse.png",
      ...clear,
    },
    {
      id: "oxgen",
      name: "0xgen Gno Explorer",
      status: "Live",
      categories: ["Explorer", "Validators"],
      score: 46,
      oneLiner: "Community validator explorer.",
      team: "0xgen",
      website: "https://gno.satai.0xgen.online/validators",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "",
      logo: "",
      ...clear,
    },
    {
      id: "oshvank",
      name: "Oshvank Gno Explorer",
      status: "Live",
      categories: ["Explorer", "Validators"],
      score: 45,
      oneLiner: "Community validator explorer.",
      team: "Oshvank",
      website: "https://explorer-gnoland.oshvank.xyz",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "",
      logo: "/logos/oshvank.png",
      ...clear,
    },
    {
      id: "nodesync",
      name: "Nodesync Gno Validator Dashboard",
      status: "Live",
      categories: ["Explorer", "Validators"],
      score: 44,
      oneLiner: "Community validator explorer and dashboard.",
      team: "Nodesync",
      website: "https://gno-validator.nodesync.top",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "",
      logo: "/logos/nodesync.png",
      ...clear,
    },
    {
      id: "utsa",
      name: "Utsa Gno Explorer",
      status: "Live",
      categories: ["Explorer"],
      score: 43,
      oneLiner: "Community explorer.",
      team: "Utsa",
      website: "https://exp.gno.utsa.tech",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "",
      logo: "/logos/utsa.png",
      ...clear,
    },
    {
      id: "bubblerumble",
      name: "Bubblerumble",
      status: "Live",
      categories: ["Game"],
      score: 55,
      oneLiner: "An on-chain last-bidder-wins game. Each bid joins a pool and resets the clock.",
      team: "",
      website: "https://bubblerumble.net/",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "gno.land/r/g1leu8d2vsplhehcfkjg50mwgdpxdkt8tztu95wr/bubblerumble",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "Player UI for the Bubblerumble realms. hooseer.com and bubblerumble.net are the same project. The sites and the realm render do not label mainnet or testnet.",
      logo: "/logos/bubblerumble.png",
      ...clear,
    },
    {
      id: "mygnoscan",
      name: "mygnoscan",
      status: "Live",
      categories: ["Explorer"],
      score: 60,
      oneLiner: "An explorer organized around deployed realms, what they import, and who calls them.",
      team: "moul",
      website: "https://mygnoscan.moul.p2p.team/",
      github: "",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "A gno.land realm page lists this URL with chain id gnoland-1. The explorer homepage itself does not print the network, so this card stays unmarked.",
      logo: "",
      ...clear,
    },
    {
      id: "gnops",
      name: "gnops",
      status: "Live",
      categories: ["Infra"],
      score: 52,
      oneLiner: "Community guides and showcases for running and observing gno.land nodes.",
      team: "",
      website: "https://gnops.io/",
      github: "https://github.com/gnoverse/gnops",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "The site does not say mainnet or testnet. One guide is about becoming a testnet validator.",
      logo: "",
      ...clear,
    },
    {
      id: "daokit",
      name: "DAOkit",
      status: "Dev",
      categories: ["Governance"],
      score: 48,
      oneLiner: "A framework for DAO proposals, voting conditions, roles, and executable actions.",
      team: "Samourai",
      website: "",
      github: "https://github.com/samouraiworld/gnodaokit",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "Separate from CommonDAO and from the Memba app. The README example uses a local dev chain.",
      logo: "",
      ...clear,
    },
    {
      id: "vscode-gno",
      name: "Gno for VS Code",
      status: "Live",
      categories: ["DevTool"],
      score: 50,
      oneLiner: "Editor extension for Gno: completion, go to definition, formatting, and tests.",
      team: "Gnoverse",
      website: "",
      github: "https://github.com/gnoverse/vscode-gno",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "Stable builds are on the Visual Studio Marketplace. An editor plugin, not a chain app.",
      logo: "",
      ...clear,
    },
    {
      id: "gno-js-client",
      name: "gno-js-client",
      status: "Live",
      categories: ["DevTool"],
      score: 56,
      oneLiner: "The official JavaScript client for calling realms and VM queries.",
      team: "Gno.land core",
      website: "https://www.npmjs.com/package/@gnolang/gno-js-client",
      github: "https://github.com/gnolang/gno-js-client",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "Package @gnolang/gno-js-client. The library is chain-agnostic.",
      logo: "",
      ...clear,
    },
    {
      id: "tx-indexer",
      name: "tx-indexer",
      status: "Dev",
      categories: ["Infra"],
      score: 54,
      oneLiner: "Indexer that stores chain data and serves blocks, transactions, and supply over JSON-RPC and GraphQL.",
      team: "Gno.land core",
      website: "",
      github: "https://github.com/gnolang/tx-indexer",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "The README example points at a retired test playground. indexer.gno.land loads as Gno Indexer and does not name a network.",
      logo: "",
      ...clear,
    },
    {
      id: "gnit",
      name: "gnit",
      status: "Dev",
      categories: ["DevTool"],
      score: 46,
      oneLiner: "Stores commits, trees, and blobs in a realm so that realm can be cloned like a Git repo.",
      team: "Gnoverse",
      website: "",
      github: "https://github.com/gnoverse/gnit",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "The documented default remote is a local dev chain.",
      logo: "",
      ...clear,
    },
    {
      id: "gnoshot",
      name: "gnoshot",
      status: "Dev",
      categories: ["DevTool"],
      score: 44,
      oneLiner: "Captures a gnoweb page and the realm's own rendered output for previews.",
      team: "Gnoverse",
      website: "",
      github: "https://github.com/gnoverse/gnoshot",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "The README says it was checked against gnoweb on gnoland-1, and the default allowlist also includes testnets.",
      logo: "",
      ...clear,
    },
    {
      id: "gnopm",
      name: "gnopm",
      status: "Dev",
      categories: ["DevTool"],
      score: 44,
      oneLiner: "Keeps a package version in gnomod.toml instead of in the directory name.",
      team: "moul",
      website: "",
      github: "https://github.com/moul/gnopm",
      x: "",
      discord: "",
      telegram: "",
      docs: "",
      worksWith: [],
      realm: "",
      alsoPath: "",
      lastUpdated: "2026-09-25",
      notes: "The README measures publish against gnoland-1 and also documents a local dev chain.",
      logo: "",
      ...clear,
    },
  ],
} satisfies Store;
